/**
 * This file is autogenerated by the `build-native-ts-icon-file.js` script.
 * Please edit that file to make adjustments.
 */

import React from "react";

import IconBack from "./icons/Back";
import IconCard from "./icons/Card";
import IconClose from "./icons/Close";
import IconDownload from "./icons/Download";
import IconForward from "./icons/Forward";
import IconKey from "./icons/Key";
import IconLock from "./icons/Lock";
import IconMapbox from "./icons/Mapbox";
import IconMeasure from "./icons/Measure";
import IconProfile from "./icons/Profile";
import IconRefer from "./icons/Refer";
import IconVideo from "./icons/Video";
import IconDynamicAccidents from "./icons/dynamic/Accidents";
import IconDynamicAdasreaction from "./icons/dynamic/Adasreaction";
import IconDynamicDashboard from "./icons/dynamic/Dashboard";
import IconDynamicDuration from "./icons/dynamic/Duration";
import IconDynamicErraticdriving from "./icons/dynamic/Erraticdriving";
import IconDynamicJourneys from "./icons/dynamic/Journeys";
import IconDynamicLanedeparture from "./icons/dynamic/Lanedeparture";
import IconDynamicNotifications from "./icons/dynamic/Notifications";
import IconDynamicRewards from "./icons/dynamic/Rewards";
import IconDynamicTailgating from "./icons/dynamic/Tailgating";
import IconDynamicTimeofday from "./icons/dynamic/Timeofday";

function iconSelector(selectorString, props) {
  switch (selectorString) {
    case "icons/back":
      return <IconBack {...props} />;
    case "icons/card":
      return <IconCard {...props} />;
    case "icons/close":
      return <IconClose {...props} />;
    case "icons/download":
      return <IconDownload {...props} />;
    case "icons/forward":
      return <IconForward {...props} />;
    case "icons/key":
      return <IconKey {...props} />;
    case "icons/lock":
      return <IconLock {...props} />;
    case "icons/mapbox":
      return <IconMapbox {...props} />;
    case "icons/measure":
      return <IconMeasure {...props} />;
    case "icons/profile":
      return <IconProfile {...props} />;
    case "icons/refer":
      return <IconRefer {...props} />;
    case "icons/video":
      return <IconVideo {...props} />;
    case "icons/dynamic/accidents":
      return <IconDynamicAccidents {...props} />;
    case "icons/dynamic/adasreaction":
      return <IconDynamicAdasreaction {...props} />;
    case "icons/dynamic/dashboard":
      return <IconDynamicDashboard {...props} />;
    case "icons/dynamic/duration":
      return <IconDynamicDuration {...props} />;
    case "icons/dynamic/erraticdriving":
      return <IconDynamicErraticdriving {...props} />;
    case "icons/dynamic/journeys":
      return <IconDynamicJourneys {...props} />;
    case "icons/dynamic/lanedeparture":
      return <IconDynamicLanedeparture {...props} />;
    case "icons/dynamic/notifications":
      return <IconDynamicNotifications {...props} />;
    case "icons/dynamic/rewards":
      return <IconDynamicRewards {...props} />;
    case "icons/dynamic/tailgating":
      return <IconDynamicTailgating {...props} />;
    case "icons/dynamic/timeofday":
      return <IconDynamicTimeofday {...props} />;
    default:
      throw new Error(
        `Invalid icon selection value: ${JSON.stringify(selectorString)}`
      );
  }
}

export const Icon = ({ selectorString, ...props }) => (
  <>{iconSelector(selectorString, props)}</>
);
