/**
 * This file is autogenerated by the `build-icon-file.js` script.
 * Please edit that file to make adjustments.
 */

import React from "react";
import { View } from "react-native";

import IconNavBack from "./icons/nav/back.svg";
import IconNavClose from "./icons/nav/close.svg";
import IconSettingAccount from "./icons/settings/account.svg";
import IconSettingCard from "./icons/settings/card.svg";
import IconSettingDownload from "./icons/settings/download.svg";
import IconSettingLock from "./icons/settings/lock.svg";
import IconSettingLogin from "./icons/settings/login.svg";
import IconSettingMapbox from "./icons/settings/mapbox.svg";
import IconSettingRefer from "./icons/settings/refer.svg";
import IconSettingRuler from "./icons/settings/ruler.svg";
import IconSettingTheo from "./icons/settings/theo.svg";
import IconSettingVideo from "./icons/settings/video.svg";

function iconSelector(selectorString) {
  switch (selectorString) {
    case "icons/nav/back":
      return <IconNavBack />;
    case "icons/nav/close":
      return <IconNavClose />;
    case "icons/settings/account":
      return <IconSettingAccount />;
    case "icons/settings/card":
      return <IconSettingCard />;
    case "icons/settings/download":
      return <IconSettingDownload />;
    case "icons/settings/lock":
      return <IconSettingLock />;
    case "icons/settings/login":
      return <IconSettingLogin />;
    case "icons/settings/mapbox":
      return <IconSettingMapbox />;
    case "icons/settings/refer":
      return <IconSettingRefer />;
    case "icons/settings/ruler":
      return <IconSettingRuler />;
    case "icons/settings/theo":
      return <IconSettingTheo />;
    case "icons/settings/video":
      return <IconSettingVideo />;
    default:
      throw new Error(
        `Invalid icon selection value: ${JSON.stringify(selectorString)}`
      );
  }
}

export const Icon = ({ selectorString, ...props }) => (
  <View style={props.style}>{iconSelector(selectorString)}</View>
);
